### ISSUE TITLE
Python version required

### ISSUE THREAD

**Issue by tvatter** [reworkd/tarsier#107]
Is 3.11 really needed? I'm asking because AWS EC2 Neuron (e.g., using trainium or inferentia chips) Deep Learning AMI use Python 3.8. Are there some specific features from 3.11+ that are required or was that included for safety?

See the [one from Amazon](https://aws.amazon.com/releasenotes/aws-deep-learning-ami-neuron-tensorflow-2-10-ubuntu-20-04/) or [that from Huggingface](https://aws.amazon.com/marketplace/pp/prodview-gr3e6yiscria2).

**Comment by asim-shrestha** [comment]
Hmm I don't _think_ it's required but let me check today

**Comment by ilyadim** [comment]
I'm not able to install it on python 3.9.6 any which way I've tried. Bout to try downgrading unless someones got suggestions. Getting a ERROR: Package 'tarsier' requires a different Python: 3.9.6 not in '<4.0,>=3.11'
