### ISSUE TITLE
Allow using the package without OCR for just getting DOM Information

### ISSUE THREAD

**Issue by sohamganatra** [reworkd/tarsier#118]
I would like to just use the tagging script and essentially pass all the elements to LLM to let it pick and choose elements to interact with to accomplish tasks. Like clicking a button or typing a field. 

I am happy to only use DOM information and don't need OCR. 

Is it possible to refactor the code so folks like me can use the package?

**Comment by craigmulligan** [comment]
I agree, I'm bumped into the same issue, to get around it I just generated a fake service_account.json and used the google OCR provider but ideally the ocr service param should be nullable.

**Comment by asim-shrestha** [comment]
Oh interesting @craigmulligan @sohamganatra mind explaining this further? So you want just a .tag_elements() method and you guys are manually extracting element info and sending to the model, or you're just wanting to use the tag_to_xpath mapping directly?

**Comment by craigmulligan** [comment]
I think the ideally the interface would be something like:

```python
tarsier = Tarsier() # note no need for OCR service
screenshot, tag_to_xpath = await tarsier.page_to_image(page)
```

**Comment by asim-shrestha** [comment]
that makes sense, can I ask what the usecase is specifically? 

Just curious what you're passing to the model at which points

**Comment by asim-shrestha** [comment]
Fixing in #128. You can use via

```python
from tarsier import Tarsier, DummyOCRService

...

tarsier = Tarsier(DummyOCRService()) # Note, the page_to_text function will return a blank page with the dummy OCR
screenshot, tag_to_xpath = await tarsier.page_to_image(page)
```

let me know if this works @craigmulligan, @sohamganatra
